import { ApiConfigInterface, apiConfig } from '../../../config/apiConfig';
export function getBase(config: ApiConfigInterface = apiConfig) {
    return `${config.protocol}://${config.host}`;
}

export function getDataApiBaseUrl(config: ApiConfigInterface = apiConfig) {
    return `${getBase(config)}/${config.dataApiUrl}`;
}

export function getAuthBaseUrl(config: ApiConfigInterface = apiConfig) {
    return `${getBase(config)}/${config.authUrl}`;
}

export const Urls = {
    login: getAuthBaseUrl() + 'login',
    forgotPassword: getAuthBaseUrl() + 'forgot-password',
    resetPasswordApi: getAuthBaseUrl() + 'reset-password',
    changePassword: getAuthBaseUrl() + 'change-password',
    lcAdd: getDataApiBaseUrl() + 'lc',
    lcFileUpload: getDataApiBaseUrl() + 'lc/upload',
    lcList: getDataApiBaseUrl() + 'lc',
    lcCount: getDataApiBaseUrl() + 'lc/count',
    lcSearchByDcNumber: getDataApiBaseUrl() + 'lc/dcnumber',
    acceptanceFileUpload: getDataApiBaseUrl() + 'acceptance/upload',
    acceptanceList: getDataApiBaseUrl() + 'acceptance',
    acceptanceUpdate: getDataApiBaseUrl() + 'acceptance',
    acceptanceCount: getDataApiBaseUrl() + 'acceptance/count',
    accpGetByBillNumberApi: getDataApiBaseUrl() + 'acceptance/billnumber',
    predictivePool: getDataApiBaseUrl() + 'lc/predictivePool',
    exporterBanksList: getDataApiBaseUrl() + 'bank',
    banksUpload: getDataApiBaseUrl() + 'bank/upload',
    currencyListCreateUpdate: getDataApiBaseUrl() + 'currency',
    acceptanceExhaustedLimits:
        getDataApiBaseUrl() + 'acceptance/exhaustedLimits',
    signUpApi: getAuthBaseUrl() + 'signup',
    getAllUsers: getAuthBaseUrl() + 'users',
    deactivateUsers: getAuthBaseUrl() + 'deactivateUser',
    updateUser: getAuthBaseUrl() + 'update-user',
    externalUserSignUpApi: getAuthBaseUrl() + 'externalUser',
    limitFileUpload: getDataApiBaseUrl() + 'limit/upload',
    borrowingBank: getDataApiBaseUrl() + 'bank/borrowingBank',
    allocateAssets: getDataApiBaseUrl() + 'acceptance/assetAllocation',
    insuranceListCreateUpdate: getDataApiBaseUrl() + 'insurance',
    libor: getDataApiBaseUrl() + 'libor',
    uploadExporterBankRates: getDataApiBaseUrl() + 'interestRate/upload',
    updateFinancingBankRates: getDataApiBaseUrl() + 'bank/interestRate',
    preLcPdfUpload: getDataApiBaseUrl() + 'preLc/upload',
    preLcList: getDataApiBaseUrl() + 'preLc',
    preLcUpdate: getDataApiBaseUrl() + 'preLc',
    preLcPdfData: getDataApiBaseUrl() + 'preLc/file',
    preLcRegenerate: getDataApiBaseUrl() + 'preLc/regenerate',
    preLcPush: getDataApiBaseUrl() + 'preLc/push',
    uploadSwift: getDataApiBaseUrl() + 'acceptance/uploadswift',
    purchaseOrderList: getDataApiBaseUrl() + 'purchaseorder',
    purchaseOrderSendForDraw: getDataApiBaseUrl() + 'purchaseorder/sendForDraw',
    purchaseOrderPublish: getDataApiBaseUrl() + 'purchaseorder/publish',
    purchaseOrderCalculate:
        getDataApiBaseUrl() + 'purchaseorder/calculateamount',
    purchaseOrderPaymentCSV:
        getDataApiBaseUrl() + 'purchaseorder/generatemakepaymentcsv',
    purchaseOrderDownloadPaymentCSV:
        getDataApiBaseUrl() + 'purchaseorder/downloadpaymentcsv',
    allAccFilterList: getDataApiBaseUrl() + 'acceptance/allfilterslist',
    approveAllAcc: getDataApiBaseUrl() + 'acceptance/approveall',
    allAccAmount: getDataApiBaseUrl() + 'acceptance/totalassetvalue',
    wipmaturityprofile: getDataApiBaseUrl() + 'acceptance/wipmaturityprofile',
    soldmaturityprofile: getDataApiBaseUrl() + 'acceptance/soldmaturityprofile',
    assetAmountsApi: getDataApiBaseUrl() + 'acceptance/assetamounts',
    borrowedAmntApi: getDataApiBaseUrl() + 'accounting/borrowedAmount',
    reconFileUpload: getDataApiBaseUrl() + 'bankrecon/uploadtxtrecon',
    reconFileList: getDataApiBaseUrl() + 'bankrecon',
    reconFileDownload: getDataApiBaseUrl() + 'bankrecon/downloadreconfile',
    assetTxnUploadApi: getDataApiBaseUrl() + 'accounting/assetsmaturitytxn',
    bankAccountListCreateUpdate: getDataApiBaseUrl() + 'bankAccount',
    paidbackAmntApi: getDataApiBaseUrl() + 'accounting/paidbackamount',
    accountDetailsListApi: getDataApiBaseUrl() + 'accounting/accountdetails',
    interestPaidApi: getDataApiBaseUrl() + 'accounting/interestPaid',
    borrowingBaseStatementApi:
        getDataApiBaseUrl() + 'purchaseorder/borrowing-base-statement',
    savePremiumPaidApi: getDataApiBaseUrl() + 'accounting/insurancePremiumPaid',
    premiumOwedListApi: getDataApiBaseUrl() + 'accounting/insurancePremium',
    totalLimitApi: getDataApiBaseUrl() + 'bank/totalLimit',
    allLcFilterList: getDataApiBaseUrl() + 'lc/allfilterslist',
    kycPdfUpload: getDataApiBaseUrl() + 'bankKyc/upload',
    kycList: getDataApiBaseUrl() + 'bankKyc',
    kycTextUpdate: getDataApiBaseUrl() + 'bankKyc',
    kycPdfData: getDataApiBaseUrl() + 'bankKyc/document',
    kycAccessEdit: getDataApiBaseUrl() + 'bank/expbankKycAccess',
    facilityPdfUpload: getDataApiBaseUrl() + 'bankFacility/upload',
    facilityList: getDataApiBaseUrl() + 'bankFacility',
    facilityTextUpdate: getDataApiBaseUrl() + 'bankFacility',
    facilityPdfData: getDataApiBaseUrl() + 'bankFacility/document',
    finbankProfile: getDataApiBaseUrl() + 'acceptance/fin-bank-profile',
    finbankBook: getDataApiBaseUrl() + 'acceptance/fin-bank-book',
    finbankMaturityProfile:
        getDataApiBaseUrl() + 'acceptance/finbankmaturityprofile',
    finbankstats: getDataApiBaseUrl() + 'acceptance/finbankstats',
    drawdownListApi: getDataApiBaseUrl() + 'drawdown',
    payeeBankDetailsListApi:
        getDataApiBaseUrl() + 'acceptance/fin-bank-exposure',
    financeReportsListApi: getDataApiBaseUrl() + 'reports',
    borrowingBaseReportUploadApi: getDataApiBaseUrl() + 'reports/upload',
    drawdownPdfDataApi: getDataApiBaseUrl() + 'drawdown/download-draw-pdf',
    acceptancePdfDataApi: getDataApiBaseUrl() + 'acceptance/download',
    lcPdfDataApi: getDataApiBaseUrl() + 'lc/download',
    summaryReportsListApi: getDataApiBaseUrl() + 'acceptance/summary-report',
    borrowingBasePdfDataApi: getDataApiBaseUrl() + 'reports/borrowing-base-pdf',
    finbankMaturityBuckets:
        getDataApiBaseUrl() + 'acceptance/finbank-maturity-buckets',
    latestReportApi: getDataApiBaseUrl() + 'reports/latest-report',
    preAcceptancePdfUpload: getDataApiBaseUrl() + 'preAcceptance/upload',
    preAcceptanceListUpdate: getDataApiBaseUrl() + 'preAcceptance',
    preAcceptancePdfData: getDataApiBaseUrl() + 'preAcceptance/file',
    preAcceptanceRegenerate: getDataApiBaseUrl() + 'preAcceptance/regenerate',
    preAcceptancePush: getDataApiBaseUrl() + 'preAcceptance/push',
    preLcCount: getDataApiBaseUrl() + 'preLc/count',
    preAcceptanceCount: getDataApiBaseUrl() + 'preAcceptance/count',
    equityFunding: getDataApiBaseUrl() + 'accounting/equity',
    equityExpenses: getDataApiBaseUrl() + 'accounting/equity-expenses',
    getProfitList: getDataApiBaseUrl() + 'accounting/profit-profile',
    profitDraw: getDataApiBaseUrl() + 'accounting/draw-profit',
    equityFundingDraw: getDataApiBaseUrl() + 'accounting/draw-equity-funding',
    equityExpensesDraw: getDataApiBaseUrl() + 'accounting/draw-equity-expenses',
    equityDrawList: getDataApiBaseUrl() + 'accounting/draw-equity',
    equityFundsBalance:
        getDataApiBaseUrl() + 'accounting/equity-funding-balance',
    equityExpensesBalance:
        getDataApiBaseUrl() + 'accounting/equity-expenses-balance',
    consentList: getDataApiBaseUrl() + 'consent',
    consentCount: getDataApiBaseUrl() + 'consent/count',
    consentUpload: getDataApiBaseUrl() + 'consent/upload',
    consentDownloadCreated:
        getDataApiBaseUrl() + 'consent/download-created-pdf',
    consentDownloadUploaded:
        getDataApiBaseUrl() + 'consent/download-uploaded-pdf',
    consentApproveReject: getDataApiBaseUrl() + 'consent/approve-reject',
    consentRevoke: getDataApiBaseUrl() + 'consent/revoke-consent',
    consentInitiate: getDataApiBaseUrl() + 'consent/initiate-consent',
    consentRequest: getDataApiBaseUrl() + 'consent/sendconsentlink',
    expImpList: getDataApiBaseUrl() + 'expimp',
    expImpUpload: getDataApiBaseUrl() + 'expimp/upload',
    expImpKycUpload: getDataApiBaseUrl() + 'expimpkyc/upload',
    expLcKycPending: getDataApiBaseUrl() + 'lc/kyc-exporters',
    impLcKycPending: getDataApiBaseUrl() + 'lc/kyc-importers',
    expAccKycPending: getDataApiBaseUrl() + 'acceptance/kyc-exporters',
    impAccKycPending: getDataApiBaseUrl() + 'acceptance/kyc-importers',
    expImpKycList: getDataApiBaseUrl() + 'expimpkyc',
    expImpKycListCount: getDataApiBaseUrl() + 'expimpkyc/count',
};
